version: '3'
services:
  reviewDb:
    container_name: database
    image: mysql

    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${REVIEW_DATABASE}
  reviews:
    container_name: reviews_component
    image: jtirelli/reviews:latest
    links:
      - "reviewDb:database"
    ports:
      - "3003:3003"
  head:
    container_name: head_component
    # build: ../head
    image: jtirelli/hero_component:latest
    links:
      - "reviewDb:head_database"
    ports:
      - "3001:3001"
  proxy:
    container_name: proxy_app
    # build: .
    image: jtirelli/proxy:latest
    links:
      - "reviews:reviews_component"
    ports:
      - "80:3000"
