version: '3'
services:
  db:
    container_name: database
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
  reviews:
    container_name: reviews_component
    image: jtirelli/reviews:latest
    links:
      - "db:database"
    ports:
     - "3003:3003"
  proxy:
    container_name: proxy_app
    build: .
    # image: jtirelli/proxy:latest
    links:
      - "reviews:reviews_component"
    ports:
      - "80:3000"
